#!/bin/sh

scripts/entrypoints/common

echo "Running linters"
scripts/lint
exit_code_lint=$?

echo "Running tests"
scripts/test
exit_code_test=$?

if [ $exit_code_lint -gt 0 ] || [ $exit_code_test -gt 0 ]
then
  exit 1
fi
